### PR TITLE
Update defconfig

### PR DESCRIPTION
**Pull request by p1ngb4ck**
Update rt2800usb to support rt5372 chip (wireless integrated to xpeed-lx3, which currently works with rt5370sta only). rt2800usb supports station mode for hostapd, so user should be able to select the desired module to use himself via blacklist!!!

### CODE REVIEW

**Comment by a4tech** [comment]
Problem is that this drvier does NOT work with WPA2 AES connection.

We have internal WiFi card, so We do not need any external supported.

Thats why We disable it, and use external working good driver.

**Comment by p1ngb4ck** [comment]
Sorry this is just not true. You can check yourself by attaching external usb wifiadapter that uses rt2800usb. It works well with wpa2 ccmp. Most routers use ccmp anyhow. It is built as module anyhow, so i dont see the point why not add rt53xx support to rt2800usb as well and simply blacklist the module for the internal wificard by default. This way there are NO cons, but only benefits: those who WANT to CAN switch modules themselves (e.g. if they want to use hostapd with thw internal wifiadapter)

**Comment by p1ngb4ck** [comment]
The "working good" driver simplay lacks essential functionality. (Station mode support)

**Comment by p1ngb4ck** [comment]
By the way you didnt understand me well. Its not about making an external usb work, but make the internal work the way that the external is now, so i dont need the extra external one anymore

**Comment by a4tech** [comment]
As I explained to You, did You try this driver ? Internal, please commpile and run it and test with 

WPA/ WPA2/TKIP/AES/HIDDEN NETWORK, it will cause lot of timeouts and problems.

Please let me have Your result.

I am not talking about EXTERNAL device, this is INTERNAL wifi problem, what is imporant.

**Comment by p1ngb4ck** [comment]
As I mentioned. I am also talking of the internal device. I want to explicitly use rt2800usb module for the internal device, so I DONT need external device any more. I was not able to recompile the module myself currently because the build-environment currently does not work as I expected on my gentoo machine here (will try on "fresh" machine with 100% percent sane environment again tonight). But, I AM currently able to use the rt2800usb module without any problems with an external adapter right now for my purposes (SoftAP), and because the same module officially supports the internal chipset officially as well, I wondered, why people cant decide themselves which module to use. This can be very easily done by adding a udev rule (added to the image by default) to bind the rt53xxsta module/blacklist rt2800usb for/ to the internal interface, so that it would NOT interfere with "average" user thats not aware of this and does not want to  use SoftAP/rt28xxusb, for the very reasons you put up (I believe you completely, dont doubt it at all.) AND (big and) : IF you take out 53xx chipset support in the rt28xxusb module like you do currently, then please also remove the module aliases for these chipsets. Currently, with the 3.8.2 kernel, you can see in dmesg its even trying to load rt2800usb by default, becuse those aliases are still there (check with modinfo, no changes by me before), before failing to load it and loading rt53xx. I really dont think this is expected/desired behaviour. I can only emphasize again : even THOUGH I dont doubt your statement regarding the stability and performance of that module, I would preferably be able to choose the module myself manually without the need for manual recompile as long as this would not have downsides (which is the case here)

PS: If you experience strange connection issues with that module, thats very likely to be related to enabled powermanagement tor usb - wifi, which doesnt really work, but can be disabled easily.

**Comment by a4tech** [comment]
Hello,

I was testing yesterday that Kernel driver, I did backport from Kernel 3.16.X too for more tests.

Please check this:

ieee80211 phy0: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2870.bin'
ieee80211 phy0: rt2x00lib_request_firmware: Info - Firmware detected - version: 0.33
IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
ieee80211 phy0: rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 10 in queue 0
ieee80211 phy0: rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 10 in queue 0
ieee80211 phy0: rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 10 in queue 0
ieee80211 phy0: rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 10 in queue 0
wlan0: authenticate with c0:c1:c0:f0:bc:26
wlan0: send auth to c0:c1:c0:f0:bc:26 (try 1/3)
wlan0: authenticated
wlan0: associate with c0:c1:c0:f0:bc:26 (try 1/3)
wlan0: RX AssocResp from c0:c1:c0:f0:bc:26 (capab=0x411 status=0 aid=3)
wlan0: associated
IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
wlan0: deauthenticating from c0:c1:c0:f0:bc:26 by local choice (reason=1)
cfg80211: Calling CRDA to update world regulatory domain
wlan0: authenticate with c0:c1:c0:f0:bc:26
wlan0: send auth to c0:c1:c0:f0:bc:26 (try 1/3)
wlan0: authenticated
wlan0: associate with c0:c1:c0:f0:bc:26 (try 1/3)
wlan0: RX AssocResp from c0:c1:c0:f0:bc:26 (capab=0x411 status=0 aid=3)
wlan0: associated
wlan0: deauthenticating from c0:c1:c0:f0:bc:26 by local choice (reason=1)
cfg80211: Calling CRDA to update world regulatory domain

ipv6                  370473  16 
rt2800usb              17610  0 
rt2800lib              78027  1 rt2800usb
rt2x00usb              10338  1 rt2800usb
rt2x00lib              42655  3 rt2x00usb,rt2800lib,rt2800usb
mac80211              310532  3 rt2x00lib,rt2x00usb,rt2800lib
dvb                 31089256  5 

If I am lucky,

I do not get constant ( thousends )

 ieee80211 phy0: rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 10 in queue 0

output what cause box hang up.

Could You test Yourself internal HW ? Perhaps my is other...

**Comment by p1ngb4ck** [comment]
I will compile and test myself as soon as I am able to compile oe-sources and build an image. tested on fresh new gentoo-machine, same error, related to parsing/expanding feed-config files.

**Comment by p1ngb4ck** [comment]
Okay somebody was so kind to compile an image with modified defconfig for me, and I have to admit you are perfectly right. I can confirm same issues. Will dig deeper into it as soon as I can.
I also know about the reasons why I couldnt build the image myself.
Whom do I have to ask for the correct Makefile of the xpeed-lx3 image? I would really prefer not to have to bother others all the time, but rather come up with solutions myself :+1: 
Thanks for your patience with me and the info!

**Pull request closed without merging**
