### PR TITLE
ffmpeg 4.1.3

### PR DESCRIPTION
**Pull request by kueken**
falls jemand die 3er Version weiter benötigt, die ist nicht angetastet und kein weiter via prefered Version genommen werden.

### CODE REVIEW

**Comment by nickersk** [comment]
which archs did you test?

**Comment by kueken** [comment]
mips Build ->Xtrend et9200
sh4 Build
arm Build cortexa15hf-neon-vfpv4 -> HD51
arm Build -> VU+ Ultimo4k

Did it again triggered, because in the ATV forum problems with previous version were addressed.
Not only the new version, but rather the 'more open' construction is important to me.
In addition avresample activated again.

ffmpeg build properly everywhere.
When hd51 I noticed the Webkit, however, that incorrectly set cflags internally there wrong. Has nothing to do with the ffmpeg version.

Do you have construction problems?

**Comment by kueken** [comment]
Hisi Boxing I do not know exactly if a change could be problematic there.
However, the version 3 can be preferred for each box.
So I changed the patches and renamed them.

**Comment by nickersk** [comment]
please, fix line endings to unix style in e2iplayer. can we test merge nextp3 first?

**Comment by kueken** [comment]
Hello

hopefully the patch will fit.
Locally I do not have the extra line at the end.
Surprising...

Of course, you are welcome to look at nextp3.
But I would actually assume that the boxes benefit from the 'more open' construction.
The construction of the ffmpeg takes a little longer, but compared to the construction of, for example, webkit arm, this is completely irrelevant.

**Comment by nickersk** [comment]
Well, when i try to merge your PR locally from yours 4.3 branch, i see the CRLF vs LF conflict, thats why we need to fix this... We misunderstood us probably. On every line I see ^M at the end of each line, this means, your editor saved file in CRLF format. I meant something like this: https://www.cyberciti.biz/faq/howto-unix-linux-convert-dos-newlines-cr-lf-unix-text-format/
or this http://sql313.com/index.php/43-main-blogs/maincat-dba/62-using-notepad-to-change-end-of-line-characters Thank You

**Comment by kueken** [comment]
Strange ...

Everything is done with gedit only in Linux.
Have it also changed directly via Github and still mistakes?
I do not really understand

**Comment by nickersk** [comment]
problem is here only: enigma2-plugin-extensions-e2iplayer.bb other files looks ok. and also pls dont use tabs in indentation, use spaces instead.

**Comment by nickersk** [comment]
try to convert it using dos2unix command. if no success i will edit it before merging. thank you.

**Comment by nickersk** [comment]
looks ok now, going to merge it to 4.3 and see users feedback. is it ok for you @atvcaptain  ?

**Comment by atvcaptain** [comment]
was ist mit aarch64 support sehe da nichts  osmio4k etc

**Comment by kueken** [comment]
https://github.com/oe-alliance/oe-alliance-core/pull/489/files#diff-efb9162dc6bcc1944bfd47da574a5727R68

**Comment by atvcaptain** [comment]
sehe bei enigma2-plugin-extensions-e2iplayer  kein aarch64

**Comment by kueken** [comment]
?
Das sollte doch ein update bzgl ffmpeg sein.
parallel hab ich dann noch den e2iplayer lauffähig gehalten, da dieser sonst wegen exeteplayer3 sonst die ffmpeg nicht erkennen würde.
Ich kann aber leider nicht das Setup vom e2iplayer bzgl aarch64 patchen ohne solche Geräte ist das schwierig.
Mir war nicht mal bekannt das es da nicht funktionierte?
Da erwartest du jetzt leider etwas zu viel von mir.

**Pull request merged**
