### PR TITLE
meta-dinobot - try gcc8

### PR DESCRIPTION
**Pull request by nickersk**

### CODE REVIEW

**Comment by nickersk** [comment]
There is missing header file in source tree. Need to investigate this. Closing PR for now.
kernel-source/drivers/common/drv/himedia/himedia_base.h:4:1
: fatal error: hi_drv_dev.h: No such file or directory

seems like broken source unpacked on my server. will do a build from scratch.

**Comment by atvcaptain** [comment]
hisilicon have own linux kernel tree we cant use normal linux header

**Comment by nickersk** [comment]
this has something to do with gcc8, it compiles ok with gcc7 and standard OE-core libc headers. maybe something in kernel drv Makefile or so. will investigate later.

**Comment by atvcaptain** [comment]
possible the macro file must change too  hisi init control with base.mak

**Pull request closed without merging**
