### PR TITLE
Add XStreamity by Kiddac build from source

### PR DESCRIPTION
**Pull request by 4l3x2k**
Please review these changes carefully because this is my first PR and .bb.

### CODE REVIEW

**Review by AbuBaniaz — COMMENTED** [review]
I would like make his skins too. Will those renderers/converters are going to be an issue if part of two packages?

**Comment by 4l3x2k** [comment]
> I would like make his skins too. Will those renderers/converters are going to be an issue if part of two packages?

Whether I understand you.

You want

- /usr/lib/enigma2/python/Components/*

and

- /usr/lib/enigma2/python/Plugins/Extensions/XStreamity/skin/*

in one package and

- /usr/lib/enigma2/python/Plugins/Extensions/XStreamity/*

except the skin part in another package?

If so I need to forward this question or at least test it. Are we going to have a DEPEND from Plugin to Skin?

**Comment by AbuBaniaz** [comment]
Please ignore my comment. Those files are not used in his other skins.

Sorry.

**Comment by 4l3x2k** [comment]
Now I see what you wanted to do. E.g. have the Renderer/Converter and skin of e.g. jedi and xstremity in one package.
Well, as you said these Renderer/Converter and skin is not used in jedi. I think in jedi it is hard coded into the plugin.

**Comment by AbuBaniaz** [comment]
That bitbake file does not build for me. I'll await for someone knowledgable to comment on way forward. Would be good to build this from source files directly as more people use receivers for IPTV

```
ERROR: Nothing PROVIDES 'python-argparse' (but /home/user/oe-a-4.4/build-enviroment/meta-local/recipes-local/enigma2-plugin-extensions-xstreamity.bb DEPENDS on or otherwise requires it). Close matches:
  python-parse
  python3-parse
  python-paste
  python RPROVIDES python-argparse
ERROR: Required build target 'enigma2-plugin-extensions-xstreamity' has no buildable providers.
Missing or unbuildable dependency chain was: ['enigma2-plugin-extensions-xstreamity', 'python-argparse']
```

From the thread on LinuxSat, these are what were meant to be installed

```
opkg install python-image
opkg install python-imaging
opkg install python-argparse
opkg install python-requests
opkg install python-multiprocessing
```

**Comment by 4l3x2k** [comment]
Thank you for checking this before merging. I do not have a build machine to test that.

This .bb file is based on the jedi maker one. I added the DEPENDS in .bb file by checking the control file of kiddacs repo.

**Comment by 4l3x2k** [comment]
I think all DEPENDS should be RDEPENDS and argparse is a module in normal standard library of python. I do not know whether this is the case for openembedded.

Leave that for now.

I hope the promising gitpod project can provide me with a build / test machine.

**Comment by 4l3x2k** [comment]
On vuduo2 with oatv-6.4 and after opkg update:

root@vuduo2:~# opkg list | grep -E "python-image|python-imaging|python-argparse|python-requests|python-multiprocessing"
python-argparse - 2.7.16-r0 - Python command line argument parser
python-image - 2.7.16-r0 - Python graphical image handling
python-imaging - 1.1.7-r5 - Python Imaging Library (PIL)
python-multiprocessing - 2.7.16-r0 - Python multiprocessing support
python-requests - 2.22.0-r0 - python-requests version 2.22.0-r0

**Comment by nickersk** [comment]
@4l3x2k these python packages have to be installed on target machine for plugin to run ok?

**Comment by 4l3x2k** [comment]
I'am not the author of this plugin. But the control file for the .ipk in the repo of the author state the python packages as DEPENDS. So my answer would be yes, these packages have to be installed on target machine.
The .bb file should contain RDEPENDS_${PN} = "python-image python-imaging python-argparse python-requests python-multiprocessing"

**Comment by 4l3x2k** [comment]
I think listing it as RDEPENDS should be fine as of openembedded sumo release which is yocto 2.5. We are at openembedded zeus release which is yocto 3.0.

Found it here: [4.13.5. Python and Python 3 Changes](https://www.yoctoproject.org/docs/3.0.3/ref-manual/ref-manual.html#migration-2.5-python-and-python3-changes)

EDIT:
Even .mo files are in the repo of the author so no need to have gettext in sysroot at buildtime.

**Comment by AbuBaniaz** [comment]
@4l3x2k 
There were some other minor changes required. Do you mind if I close this request and commit the one Nickersk adapted?

**Comment by 4l3x2k** [comment]
@AbuBaniaz 
Ok, no problem.

**Comment by AbuBaniaz** [comment]
I have added here as some images are still on 4.3
https://github.com/oe-alliance/oe-alliance-core/commit/465a178715d56fb0bb6cb9aefae9b820d71b28f5

It will be added to 4.4 branch and higher when the next merge is done.

**Comment by 4l3x2k** [comment]
Yeah. I saw that you removed it in 4.3 branch from 3rd party feed. I was also thinking about that as most of the changes are merged to newer version.

Nevertheless, nice to see that.

Now hotios picons :-D

**Pull request closed without merging**
