### PR TITLE
nextp3 - readded libupnp 1.6, bumped samba to 4.7.6

### PR DESCRIPTION
**Pull request by nickersk**
please update openembedded modules first ...
whats in:

- libupnp - readded libupnp version 1.6, because it has been removed from openembedded but djmount and ushare wont compile with libupnp 1.8.x (only these two archaic apps use it, so maybe they should be  removed or replaced soon
- samba bumped to latest openembedded 4.7.6 version

### CODE REVIEW

**Comment by atvcaptain** [comment]
yes we must check debian for upnp addons or find ready patches

**Comment by nickersk** [comment]
i managed djmount to use external libupnp, but the problem is with threadutil files. i spent over 1 day to find patches for libupnp 1.8 with no success (djmount had been removed from debian too).

**Comment by atvcaptain** [comment]
here the patches: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884243

**Comment by atvcaptain** [comment]
i have read two patches fix it

**Comment by nickersk** [comment]
thx, i'll try

**Comment by nickersk** [comment]
no way to get it compile correctly... i dont have any ideas more. i'll try to find and test some forks on github.

**Pull request merged**
