### PR TITLE
add python-typing as depend

### PR DESCRIPTION
**Pull request by kueken**
you need typing as follow this commit
https://github.com/oe-mirrors/streamlink-27/commit/9642f2d553fda02e3eaab4831aefa250d953fed0

https://github.com/oe-mirrors/streamlink-27/blob/master/src/streamlink/plugin/plugin.py#L8

### CODE REVIEW

**Review by nickersk — COMMENTED** [review]
hi, please create bbappend for py-typing in recipe-devtools/python to include pkg split and update your PR. thx

**Comment by kueken** [comment]
python typing is part of meta Openembedded

https://github.com/openembedded/meta-openembedded/blob/zeus/meta-python/recipes-devtools/python/python-typing.inc

**Comment by kueken** [comment]
Ok, I think I didn't understand it at first.
I will update it.
Wait a little

**Comment by kueken** [comment]
hopefully it's okay that way.
greetings

**Pull request merged**
