### PR TITLE
4.2 prepared for actual openembedded git, master branch - for merge to nextp3

### PR DESCRIPTION
**Pull request by nickersk**
modified for actual openembedded git, master branch... openatv build succesfull on ubuntu server and tested ok on vusolose.

### CODE REVIEW

**Comment by nickersk** [comment]
this PR includes previous merge of 4.2 to nextp3.

**Comment by atvcaptain** [comment]
thx i see you remove patches mtd we need this for dreambox, or opkg, this nned too or opkg fails install ipks, one patch remove for old kernel version in glib must add too, wget and iproute must test need or not check old commit from spacerat he add it

**Comment by nickersk** [comment]
ahm clear, but those patches will need to be rewritten, because actual openembedded is very sensitive on fuzzes...etc.. also many files just not exists in new versions of recipes.

**Comment by atvcaptain** [comment]
now you can test, i have update oe.core ,some new issue now include :)

**Pull request merged**
