### PR TITLE
Update rytec.sources.xml

### PR DESCRIPTION
**Pull request by doglover3920**
Fixed typo's
Placed the xz versions at the top
Merged UKsat and Virgin sources
Merged the Telenet and Belgium sources
Removed obsolete items.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Willy, the plugin has been adapted to use xz files. There is no need to wait another three months to remove the .gz sources. Please consider removing them now.

You are already getting lots of questions, might as well get rid of the .gz files in the source and people can use the .xz ones. If you wait till January, you will have another round of "sources don't work, can I have updated plugin...." threads

**Comment by doglover3920** [comment]
This is so.  But I have said it will be supported until 31/12/2017.
So I will leave it at this.

I will update this file in a month or so.  At that time the gz files will be removed.

**Comment by Schimmelreiter** [comment]
For me, the old sources didn't work anymore already, so they can really go.

Better a miserable end than endless misery ...

**Comment by AbuBaniaz** [comment]
Do you mind if I manually remove them after merging? The PLI version can keep the gz files

**Comment by AbuBaniaz** [comment]
@Schimmelreiter 
I made the changes here if you want to pick them into this branch
https://github.com/oe-alliance/oe-alliance-core/commit/baa45076e54d300aecc0035fb7f3456690a825b8

**Comment by Schimmelreiter** [comment]
Done

**Comment by AbuBaniaz** [comment]
We forgot to bump the PV. Done now.
4.0 https://github.com/oe-alliance/oe-alliance-core/commit/d703c3257cc05dba233094ad0ee01f1554eba7eb
4.1 https://github.com/oe-alliance/oe-alliance-core/commit/fb0835232c5cf77f245d43aa94e8b078bc72ed9f

**Pull request merged**
