### PR TITLE
add support for WinTV-dualHD

### PR DESCRIPTION
**Pull request by kueken**
tnx @ https://forums.openpli.org/topic/84013-vu-duo-4k-hauppauge-wintv-dualhd-patch-and-driver/?view=findpost&p=1355421

### CODE REVIEW

**Comment by kueken** [comment]
ok, verstehe.
Ich mach wieder zu.

**Comment by nickersk** [comment]
hi, was this tested?

**Comment by kueken** [comment]
Hi

I linked the tester.
I cannot test it myself because the devices are not available to me.

If someone has the box here, they are welcome to test it.
But somehow there is no feedback here, so I'll close it again.

**Comment by nickersk** [comment]
that's because we try to find somebody who can test it before trigerring kernel rebuild ...

**Comment by kueken** [comment]
The construction works flawlessly.
Will everything work with the WinTV Stick?
I don't have that either.
The patch is neat and doesn't damage the other patches.
I also patched Gigablue, because from my point of view the box is in circulation more often.
At least that's how it looks in ATV and HDF.

it#s just a hobby
If you want, you can also take a look at 4.4.1 from me.
So last stand Zeus and updates around python ...
But I think everything is going in the direction of py 3.
greetings

**Comment by kueken** [comment]
@nickersk 
can you check this patch for possible fix Problems with mips?
https://github.com/kueken/oe-alliance-core/commit/dd276bc4428be39aa29b16c8991d07309cc02fbb

Branch 4.4

**Comment by nickersk** [comment]
possible, but since glibc is very complex testing on affected machine(s) has to be done for sure. and as only mipsel seems to be affected i would put patch to SRC_URI_append_mipsel = " file://..."

**Pull request closed without merging**
