### PR TITLE
The rtl8xxxu drfiver does not actually work well with rtl8192cu chipsets.

### PR DESCRIPTION
**Pull request by original-birdman**
So install rtl8192cu as well for liuxwifi - it will be used in preference.

### CODE REVIEW

**Comment by original-birdman** [comment]
For examples of problems with rtl8xxxu for rtl8192cu see:
https://github.com/pvaret/rtl8192cu-fixes/issues/76
and 
http://www.world-of-satellite.com/showthread.php?54512-Wireless-adaptor-for-HD51
(the latter is why I'm posting this, and is where it was tested).

**Comment by atvcaptain** [comment]
we use only new driver

**Comment by original-birdman** [comment]
Why would you only use a driver that doesn't work, when there is a driver which does work?
That's just silly.....

**Comment by atvcaptain** [comment]
here works np

**Comment by fat-tony** [comment]
I use an rtl8192cu dongle, originally supplied with Miraclebox Twin HD. Did not work with OpenATV or with OpenViX on the mut@nt HD51 which is on 4.x kernel. Subsequent testing with OpenViX showed that the rtl8xxxu driver recognised the rtl8192cu dongle but did not operate it correctly. Only fix was to install rtl8192cu kernel driver, which takes preference over rtl8xxxu, thus @birdman's pull request.

**Comment by original-birdman** [comment]
> here works np

Really? On what kernel version? Are you actually using one with `linuxwifi` set?

Needs to be kernel `4.7+`, IIRC.

**Comment by atvcaptain** [comment]
no from 8192 1000 models exist my models works with universal, looks uk models not, so we add two drivers universal and Proprietary

**Pull request closed without merging**
