### PR TITLE
Airdigital H9 - add facility to move root to SDcard/USB

### PR DESCRIPTION
**Pull request by TwolDE2**
Apart from the update to H9.conf only other changes are to OpenViX Distro files and OpenViX mainstream code that allows the transfer of the root files between Nand and SDcard to mitigate limited flash memory issue on H9.

### CODE REVIEW

**Comment by atvcaptain** [comment]
wait for real multiboot comes from zgemma

**Comment by ViX-Sicilian** [comment]
Why close this? This could be accepted and removed once Zgemma actually release a 'real multi-boot'. At the moment this is an excellent solution.

**Comment by ViX-Sicilian** [comment]
This is a really good easy to use feature for anyone to use, no need to use scripts. Allows user to flash image to NAND. The then easily move image to SD card. Once done user can select to boot from NAND or SD card. Once on SD card users can install BOTH Kodi and Stalker.

**Comment by ViX-Sicilian** [comment]
I've re-opened this so that it can be discussed before closing or accepting it.

**Comment by ViX-Sicilian** [comment]
This will not affect other teams at all if they choose not to use this feature. Other team images will just build and boot as usual so do not see any real reason as to not to accept this.

**Comment by atvcaptain** [comment]
create a client plugin so all teams can used it, i have speak to zgemma no multiboot comes for h9 , so we can add own solution and must not wait

**Comment by ViX-Sicilian** [comment]
I think teams will be able to pick in from OpenViX GIT once the needed changes are commited. I think will be a bit difficicult to create a plugin for all, we all have variations of how we mutli-boot. This isn't exactly multiboot though. Basically works like this in OpenViX:

1) Flash image to NAND.
2) Add SD card, user will have option to prepare SD card, files get copied from NAND to SD card.
3) Reboot.
4) User has option to boot from SD card or NAND. From SD you can boot back to NAND image.

You'll understand better once E2 stuff is committed.

Twol is checking something before I accept this PR.

**Comment by atvcaptain** [comment]
user need flash online , image backup , before you add any create a solution

**Comment by ViX-Sicilian** [comment]
I’ll post some screenshots tomorrow.

**Pull request merged**
