### PR TITLE
improve gittag

### PR DESCRIPTION
**Pull request by jbleyel**
```
old : <tag>-<tag count>-g<gitref>
new: <tag>-<commit count>+<gitref>

```
The new string is more like GITPKGV.

### CODE REVIEW

**Comment by nickersk** [comment]
looks good to me

**Review by nickersk — APPROVED** [review]

**Comment by jbleyel** [comment]
Hi @Huevos , please check and approve. Thanks

**Comment by Huevos** [comment]
Is that right having "ver =" in line 16 and 17?

https://github.com/oe-alliance/oe-alliance-core/pull/733/files/f12baa4d63b8aade65c50aee16f778038b25eff4#diff-27ef5fb58a54b7c7e14a7b18b974efc0ba68ca220e469512580cf671a9927068R116-R117

**Comment by jbleyel** [comment]
> Is that right having "ver =" in line 16 and 17?
> 
The result of :
`
ver = gitpkgv_drop_tag_prefix(d, output)`

is only the tag name.

and the result of :

`ver = "%s-%s+%s" % (ver, commits, vars['rev'][:7])`

is 

`<tag>-<commit count>+<gitref>`

**Comment by Huevos** [comment]
I can't see a problem with this.

Only way to know for sure is try it.

**Pull request closed without merging**
