### PR TITLE
Update azbox.inc

### PR DESCRIPTION
**Pull request by persianpros**
Remove obsolete switch.

### CODE REVIEW

**Comment by atvcaptain** [comment]
??  https://github.com/dazulrich/gstreamer1.0-plugin-multibox-dvbmediasink/blob/master/configure.ac#L272

**Comment by persianpros** [comment]
Hmm it gives me unknown swtich ...

**Comment by atvcaptain** [comment]
dazulrich i see have remove azboxhd changes, i have no idea works or not

**Comment by persianpros** [comment]
I did my test with https://github.com/oe-alliance/oe-alliance-core/blob/4.1/meta-brands/meta-azbox/recipes-bsp/gstreamer1.0-plugin-azbox-dvbmediasink.bb#L13 but it said unknown switch.

**Pull request closed without merging**
