### PR TITLE
Open Vision build support (5.1)

### PR DESCRIPTION
**Pull request by persianpros**
Although we know this PR won't be merged, still we wanted to show OV is open and could be builded with OE-A so https://github.com/oe-alliance/bootmenu/commit/692001f6f804fbc05f2c8e81ba0e6f320988aeda is complete BS and once again ViX devs showed how much they can fuck up just like how they fucked PLi's e2 which is not upstream anymore thanks to them.

Just to let you know we're using https://github.com/OpenVisionE2/bootmenu so reverting that commit is not important for us and you can keep it as sign of stupidity which we hope you do, this PR demonstrates how unreliable OE-A repos actually are and how ViX's stupid decisions (as always) could hide their lies and trick you.

First we thought bootmenu repo is a repo that manufacturers (like @zgemma-star) decide about it not just some guys so we learned our lesson and decided to use our https://github.com/OpenVisionE2/bootmenu with all deleted images restored, instead.

Again ViX's behaviour is predictable so it's just a matter of time for them to come up with another lie or whatever they find to hijack the discussion and move your minds of the actual problem.

Good luck and lets hope not to see childish acts in future.

### CODE REVIEW

**Comment by persianpros** [comment]
https://github.com/OpenVisionE2/ov-expansion for building OV without this PR.

**Comment by jbleyel** [comment]
Hi @RobvanderDoes , what’s wrong with this pr? Is it break other images?

**Comment by RobvanderDoes** [comment]
The commit text. We have no intention to spoil energy on people who behave like that.

**Comment by persianpros** [comment]
@RobvanderDoes 

If you don't know enough let me teach you more about git, the commit is https://github.com/oe-alliance/oe-alliance-core/pull/778/commits/29903fe42a98918eb38ccaf102b65a72de0737a6 without any description.

What you see here is PR description but ViX is well known for being stupid remember?

You can merge the PR without the description, 1 week of working with github could have thought you that.

**Comment by persianpros** [comment]
@jbleyel 

We're willing to add more support to OE-A regarding OV compiling but as you see ViX problems is like a "never ending story".

I didn't want to make this PR complex so it's without our skin and is just like a pure image with our e2.

**Comment by Huevos** [comment]
No idea why you want to keep blaming OpenViX. It was an OE-Alliance decision discussed beforehand.

**Comment by Huevos** [comment]
Also, OpenVision is not a member of OE-A so why do we need OpenVision build support here? Please add to your own public repo.

**Comment by persianpros** [comment]
@Huevos 

You're missing the point, allowing more images to be builded with OE-A means more contribution to OE-A and more packages on your feed.

**Comment by zgemma-star** [comment]
Bootmenu should been available for all images. Openvision, Openpli and other non OE-Alliance members should have the option to add their images in the list.

**Comment by RobvanderDoes** [comment]
Not sure why that "should be", but anyway an other decision has been made.

**Comment by persianpros** [comment]
@zgemma-star That's the reason we're using https://github.com/OpenVisionE2/bootmenu because OE-A version isn't for all so I suggest you do the same and allow your users to access to all images not just what OE-A likes.

**Comment by Huevos** [comment]
> Bootmenu should been available for all images. Openvision, Openpli and other non OE-Alliance members should have the option to add their images in the list.

BootMenu is for all  open source images.

**Pull request closed without merging**
