### PR TITLE
enigma2 - fix automake deps make using older depout.m4 macro

### PR DESCRIPTION
**Pull request by nickersk**
- this should be implemented to enigma DEV branch maybe ...
- there sure is other way to achieve this, but i didnt find am--depfiles to be documented anywhere
- use this: http://git.savannah.gnu.org/cgit/automake.git/tree/m4/depout.m4?id=5de75f07dc12f3ff73ddecf92ff23694b120fe78
instead of this: http://git.savannah.gnu.org/cgit/automake.git/commit/m4/depout.m4?id=6a675ef17edf7109da189f5ae70e2dc6b7665896

### CODE REVIEW

**Comment by atvcaptain** [comment]
yes better we merge patch to dev branch, this is cleaner, great work find a solution

**Comment by atvcaptain** [comment]
splitt your merge and add e2 patch to dev branch

**Comment by nickersk** [comment]
we forgot other distros e2. every distro should adapt this, else broken build will come.

**Comment by atvcaptain** [comment]
all other merge it, when we have nextp3 ready

**Comment by nickersk** [comment]
ok, just a reminder... :-)

**Comment by TwolDE** [comment]
OK, but what do the distro‘s have to do to handle this change ..... and Yes I have read your post but still do not see it.

**Comment by nickersk** [comment]
They have to adapt it to their E2.

**Comment by arn354** [comment]
The referenced commit mentions it:
Quote: look at openatv/enigma2@904d338

**Comment by TwolDE** [comment]
Many thanks - I should take more time reading the comments

**Pull request closed without merging**
