### PR TITLE
Update ffmpeg_3.2.1.bb

### PR DESCRIPTION
**Pull request by kueken**
fetcher-Fehler

### CODE REVIEW

**Comment by arn354** [comment]
Sorry there is something wrong on your side.
I downloaded https://www.ffmpeg.org/releases/ffmpeg-3.2.1.tar.xz  and did the Hashcheck which is exactly like in original recipe of oe (which i basically only copied and applied some changes):

**Comment by arn354** [comment]
see original bitbake recipe commithash http://git.openembedded.org/openembedded-core/tree/meta/recipes-multimedia/ffmpeg/ffmpeg_3.2.1.bb#n19

**Comment by kueken** [comment]
Sorry

hab den Hashwert nach bz2 aufgelöst und es schlichtweg verbaselt es nach xz anzupassen.
Mein Fehler
Grüße

**Comment by arn354** [comment]
Kein Problem :)

**Pull request closed without merging**
