### PR TITLE
Integrate groupedservices to oe core instead of enigma2 distros

### PR DESCRIPTION
**Pull request by jeepcook**
Hello,

Currently the subservices management is made in each distro with the /usr/share/groupedservices file and/or /etc/enigma2/groupedservces file, this last one is the one used if exists, if not it's the one under share that is used. 

My request would be to manage this file into oe core instead of each enigma2 distro. It's a common file (like tuxbox files are), the updates are not the same if a distro dev put changes in his distro but not in others. So we have different files contents depending on dev's distro commits.

I think this functionality has to be update. Currently the subservices are displayed by pressing the green button (enable by default or to configure with hotkeys configuration). The names of the subservice channels are not displayed, only their epg, so it's difficult to know which channel is corresponding to the displayed epg. If a channel has no epg, we are unable to select this subservice because it is not displayed in the list.

So, a way to update functionality:
- display subservices names and their epg if exist, the name has to be extract from lamedb unless a manual naming has been made in the groupedservices file (name after the ServiceRef# or another way like DESCRIPTION: for example).
- iptv subservices (example Bfm Lyon, Bfm Paris as subservices to Bfm Tv) can be managed too, it's the case today, but if there is no service from lamedb in the groupedservices list, the display of the subservices list is broken.

I think it's an interresting dev project, it has never been completed so the current usage is not easy and friendly.

We have a lot of possible subservices (sky, france 3, BFM tv, Hd+......)

What do you think about that ? If you have questions about this functionality, please contact me.

Hop my request is understanding.

Thanks !

Edit, example for BFM TV (lamedb services + iptv official services)
# BFM TV
1:0:19:206D:432:1:C00000:0:0:0:		#BFM TV CSAT
1:0:19:203:2:20FA:DDE0000:0:0:0:	#BFM TV PLS
1:0:19:BC4:4E84:55F:DDE0000:0:0:0:	#BFM TV FRANSAT
4097:0:19:71F:2904:55F:DDE0000:0:0:0:https%3a//bfmparishdslive-lh.akamaihd.net/i/BFMPARIS:KB@429747/master.m3u8		#BFM PARIS IPTV
4097:0:1:45B:526C:55F:DDE0000:0:0:0:https%3a//live.creacast.com/grandlilletv/smil%3agrandlilletv.smil/playlist.m3u8	#BFM LILLE IPTV
4097:0:1:9104:0:0:0:0:0:0:https%3a//live.creacast.com/grandlittoral/smil%3agrandlittoral.smil/playlist.m3u8			#BFM GRAND LITTORAL IPTV
4097:0:19:723:2904:55F:DDE0000:0:0:0:https%3a//bfmlyon-lh.akamaihd.net/i/BFMLYON:KBS@797041/master.m3u8				#BFM LYON IPTV
1:0:19:206F:432:1:C00000:0:0:0:		#BFM BUSINESS CSAT

### CODE REVIEW

**Comment by jeepcook** [comment]
Hello, could you please explain me why there are 12 commits attached to this request, but some seem to have no link with the request (epgimport commits for examples).
Thanks

**Comment by atvcaptain** [comment]
first update your fork to the last version and send the pull request new, , after this we can merge

**Comment by jeepcook** [comment]
> 
> 
> first update your fork to the last version and send the pull request new, , after this we can merge

I searched how to do that but I can't find the process... :-((

**Comment by atvcaptain** [comment]
fork new and add you changes again

**Comment by jeepcook** [comment]
> 
> 
> fork new and add you changes again

Ok but is there any chance that this development will be made ? Nobody has answered about an update dev.

**Comment by jeepcook** [comment]
done

**Pull request closed without merging**
