### PR TITLE
Modernise openATV spinner

### PR DESCRIPTION
**Pull request by wedebe**
Modernise openATV spinner

This change replaces the 8-year-old Windows/IE style `busy` blue circle with a smarter, grey-based minimally-animated openATV logo.

[EDIT:]
Preview (not as-rendered size):

https://user-images.githubusercontent.com/9741693/232504934-70ebbda4-ac17-4b26-8b5c-fff397c69cfa.mov

### CODE REVIEW

**Comment by jbleyel** [comment]
Are you sure?

All the images looks the same.

**Comment by wedebe** [comment]
> Are you sure?
> 
> All the images looks the same.

The inner circle is animated.

**Comment by IanSav** [comment]
It is very subtle.  Without your video I didn't pick the animation.

What about spinning the circular part of the logo around a vertical axis?

**Comment by wedebe** [comment]
> It is very subtle. Without your video I didn't pick the animation.
> 
> What about spinning the circular part of the logo around a vertical axis?

I've just pushed a commit which enlarges the image by 50% to make the animation more obvious. Axis-spinning is pretty much a late 1990's/early 2000's web graphic technique 😬

I tried rotating the whole globe clockwise but it looked ugly as hell 😵‍💫

**Comment by jbleyel** [comment]
Hi @wedebe, do you have tested your new spinner in HD, FHD and UHD?

**Comment by wedebe** [comment]
> Hi @wedebe, do you have tested your new spinner in HD, FHD and UHD?

I don't have a UHD display but will screenshot using OWIF - what's the most suitable shell command to trigger a spinner?

**Comment by wedebe** [comment]
> > Hi @wedebe, do you have tested your new spinner in HD, FHD and UHD?
> 
> I don't have a UHD display but will screenshot using OWIF - what's the most suitable shell command to trigger a spinner?

@jbleyel @IanSav , can someone with the appropriate hardware please test on my behalf or can we merge and - in the very unlikely event it's not quite right - I'll fix if necessary

**Comment by jbleyel** [comment]
> @jbleyel @IanSav , can someone with the appropriate hardware please test on my behalf or can we merge and - in the very unlikely event it's not quite right - I'll fix if necessary

My fault, the spinner is OSD so that means we have only HD and FHD.

You can use you own spinner and you can also add spinner to a skin.
Changing the default spinner is not good imho.

**Comment by IanSav** [comment]
Which spinner do you intend to replace?

The spinner you posted in the first post looks okay to me.  @atvcaptain should be consulted as I believe that he is the guardian of the OpenATV corporate imagery.

I should note that I use the OverlayHD skin and the spinners that it includes.

**Comment by wedebe** [comment]
> Which spinner do you intend to replace?
> 
> The spinner you posted in the first post looks okay to me. @atvcaptain should be consulted as I believe that he is the guardian of the OpenATV corporate imagery.
> 
> I should note that I use the OverlayHD skin and the spinners that it includes.

Replaces this spinner:

https://github.com/oe-alliance/oe-alliance-core/blob/c56b8e169771d61e1b99115df4b6236b4df05267/meta-oe/recipes-distros/openatv/spinner/files/wait1.png

which is the default on OpenATV MetrixHD.

**Pull request closed without merging**
