### PR TITLE
Update enigma2-plugin-extensions-xstreamity.bb

### PR DESCRIPTION
**Pull request by 4l3x2k**
Plugin now python3 compatible.

### CODE REVIEW

**Comment by nickersk** [comment]
hi, please make PR to nextp3 branch (4.3 and 4.4 are py2). thx

**Comment by 4l3x2k** [comment]
Hi,
I think it is python2 and python3 compatible. See https://www.linuxsat-support.com/thread/142258-x-streamity-xtream-codes-iptv-player/?postID=566580#post566580
Or is that a design/politic/architecture decision? If yes, I'll create a PR to nextp3 branch.

**Comment by nickersk** [comment]
it is because of meta-oe layer.conf, there is no ${PYTHON_PN} set in 4.3 and 4.4. see https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/conf/layer.conf and then in nextp3 branch around line no. 26

**Comment by 4l3x2k** [comment]
All right. Thank you for advise.
This PR will be moved to nextp3 branch.

**Pull request closed without merging**
