### PR TITLE
Rename to 1.4.%, as openembedded-core is using version 1.4.48.

### PR DESCRIPTION
**Pull request by original-birdman**

### CODE REVIEW

**Comment by original-birdman** [comment]
openembedded-core change was on 29 Nov:

http://git.openembedded.org/openembedded-core/commit/meta/recipes-extended/lighttpd?id=01ff1c5929ef9293097da00b810ab94ceaf4a0dd

**Comment by Schimmelreiter** [comment]
We don't auto-follow oe-core ...

**Comment by original-birdman** [comment]
This isn't an "auto-follow" - it's a bug-fix.
Without it `nextp3` won't build.

**Comment by Schimmelreiter** [comment]
Ah, ok, it's for nextp3, didn't notice that :)

**Pull request merged**
