### PR TITLE
The rtl8xxxu drfiver does not actually work well with rtl8192cu chips…

### PR DESCRIPTION
**Pull request by original-birdman**
…ets.

So install rtl8192cu as well for liuxwifi - it will be used in preference.

Added here just for OpenVix as captain reckons that dogma is preferable to a working NIC.

### CODE REVIEW

**Comment by atvcaptain** [comment]
nice rob now support all

**Comment by original-birdman** [comment]
> bitbake parses ALL folders

I didn't know that.
What's the point of having distribution-named config directories if every distro uses them? 

The change is *needed* everywhere, but the change to the _global_ config file was rejected.

**Comment by original-birdman** [comment]
> You should have done something like - but locally checked first ;)
> RRECOMMENDS_openvix_${PN}

That produces an error in the build (in function `do_package_ipk`, while running `do_package_write_ipk` - no sign of what the error is, just says the function was in ERROR and stops...)

`RRECOMMENDS_${PN}_openvix` works though.

**Comment by atvcaptain** [comment]
i add other solution wait

**Pull request merged**
