### PR TITLE
Set remote's Radio button to toggle TV/Radio mode

### PR DESCRIPTION
**Pull request by bigroma73**
odinm7 model (GI Genius) has ONLY TV/Radio button on remote. E2 recognize this button as Radio button. Tuner can't return from radio mode to TV mode. This patch set radio button to toggle mode

### CODE REVIEW

**Comment by atvcaptain** [comment]
which distro you use in openvix and openatv we have a toggle function in e2

**Comment by bigroma73** [comment]
I use openpl distro.

**Comment by atvcaptain** [comment]
i add this in the next days for you

**Comment by atvcaptain** [comment]
function include

**Comment by andyblac** [comment]
imo, the drivers should be mapping the TV button to 'KEY_TV2' so it can be independently set to a keymap as a toggle switch, we should not be patching these types of things.

just my opinion.

Andy.

**Pull request closed without merging**
