### PR TITLE
Nextp3 update to current ViX python3 files

### PR DESCRIPTION
**Pull request by TwolDE2**

### CODE REVIEW

**Comment by atvcaptain** [comment]
py3 addons not vix addons we revert this commit

**Comment by TwolDE2** [comment]
Plugins: 
QUADPIP  was integrated into ATV E2 and OpenPli only use py2, so this is needed by ViX to support py2/py3.
ServiceHiSilicon is modded for  OpenViX a bit like your version of serviceapp which doesn‘t support OpenPli/OpenViX ITAP and is only  for ATV and its clones - so is needed  . If you want me to add a version of serviceapp that supports both ATV and ViX then say so and I will provide a generalised version.

**Comment by jbleyel** [comment]
Please make the pull again without the change for "enigma2-plugin-systemplugins-quadpip".

**Comment by TwolDE2** [comment]
Ok - thanks will do.

**Pull request merged**
