### PR TITLE
Revert to kernel 4.0.1 (and remove linuxwifi option) from OpenViX bui…

### PR DESCRIPTION
**Pull request by original-birdman**
…lds *ONLY* for the et4x00, et8000 and et10000 models.

This is to overcome the problems seen with the 4.8.3 kernel, as reported at:
- https://github.com/oe-alliance/oe-alliance-core/issues/163
- https://github.com/oe-alliance/oe-alliance-core/commit/e131668d76b81bb7c14983f6b5cc76e7df6d1c4e

Note that this has been tested on builds of OpenVix for all 3 models (builds 4.0.1 kernels) and OpenATV (builds 4.8.3 kernels).
It appears that only OpenViX is interested in providing working kernels for USB tuners.

### CODE REVIEW

**Comment by original-birdman** [comment]
And when committing this, please update the main module so that it knows this sub-module has been changed - thanks....

**Comment by atvcaptain** [comment]
we dont revert this why ?, send issue logs to xtrend and wait for a fix when you have a issue, here all ok

when only for vix add the changes to openvix.conf and not in all the bb files !

**Comment by ViX-Sicilian** [comment]
Why did you close?? This was only for OpenViX!

+# Set OpenViX to use 4.0.1
+#
+PREFERRED_VERSION_linux-etxx00_openvix = "4.0.1"
+PREFERRED_VERSION_linux-libc-headers_openvix = "4.0"

**Comment by ViX-Sicilian** [comment]
Now another pull request has to be submitted because this cannot be re-opened.

**Comment by atvcaptain** [comment]
first make the change in meta-local on your build server, and not spam the git , we discuss this with wte and not add strange bb changes only for one distro WAIT

**Comment by original-birdman** [comment]
WAIT for **what**?

This is already broken for OpenViX - we need a fix _now_, not when you decide that ViX can have it.
It doesn't affect any other distro.
What is your problem? 

[And _still_ no-one wants to say where the broken drivers for the 4.8.3 kernel came from, as they are not on the official Xtrend git]

**Comment by original-birdman** [comment]
> we dont revert this why ?, send issue logs to xtrend and wait for a fix when you have a issue, here all ok

Please send a log or image of an Xtrend 4.8.3 kernel running with a Sundtek or PCTV nanostick USB tuner.  A system running _without_ one doesn't count as "OK".
And I haven't reverted anything.  I've added a different choice for one build only.

**Comment by RobvanderDoes** [comment]
The 4.8.3 kernel drivers have never been officially released by Xtrend, only as test drivers.

**Comment by original-birdman** [comment]
So we tested it. It doesn't work. But we can't get the working kernel re-instated for ViX?

Not such much an Alliance, more of a Dictatorship...

**Comment by original-birdman** [comment]
> first make the change in meta-local on your build server, and not spam the git , we discuss this with wte and not add strange bb changes only for one distro WAIT

I wasn't spamming the git. A few months back I made a change in `openvix.conf`(I think) that, given the name I reckoned only affected OpenVix. I was told that this was not the case and that for OpenVix-only changes I should tag values with "_openvix".  This is what I did here. Now I'm told this is spamming git.....

Might I make a (generic) suggestion here?  That there _should_ be somewhere in the configuration files where distribution can add modifications which no other distro will pick up? And that _they_ have control over the its contents (along with responsibility for it staying in step with the rest of the git modules).

Putting a change into meta-local is useless for providing a distribution that others can build, isn't it?

And _still_ no-one has been able to show a build with this test kernel running with USB tuners.

**Comment by bbbuk** [comment]
As an end-user with a Et8000 and reading the comments regarding this both here and the original oe-a github, there is clearly a problem with latest kernel and I don't see how you can wait for the manufacturer to fix it considering they didn't break as they officially use an older kernel and didn't cause this problem to start with.  The source for the new kernel is held on server that openatv use (and probably own if I looked into further).  Would it not make sense to stick with older kernel until such time as a fix is found - whether by Xtrend or anyone else!!!!

**Pull request closed without merging**
